# Generated by Django 4.2.22 on 2025-06-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0002_delete_subtopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subject_images/'),
        ),
    ]
